[tools]
# "github:Canop/broot" = "latest"
# "github:fletcher/MultiMarkdown-6" = "latest"
# markdownlint-cli2 = "latest"
# tflint = "latest"
bat = "latest"
delta = "latest"
direnv = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
git-cliff = "latest"
jq = "latest"
just = "latest"
python = "3.14"
"github:BurntSushi/ripgrep" = "latest"
shellcheck = "latest"
starship = "latest"
swiftlint = "latest"
uv = "latest"
zoxide = "latest"

[settings]
python.uv_venv_auto = "source"
