board:
  id: 448
  name: DSF board
  type: simple
epic:
  name: ""
  link: ""
installation: Cloud
issue:
  fields:
    custom:
    - name: Rank
      key: customfield_10011
      schema:
        datatype: any
    - name: Flagged
      key: customfield_10024
      schema:
        datatype: array
        items: option
    - name: Development
      key: customfield_10000
      schema:
        datatype: any
    - name: Issue color
      key: customfield_10107
      schema:
        datatype: string
    - name: Start date
      key: customfield_10093
      schema:
        datatype: date
    - name: Link to Prefect Backfill Job/DataDog Log
      key: customfield_10643
      schema:
        datatype: string
    - name: Data Store
      key: customfield_10644
      schema:
        datatype: option
    - name: Link to reason for backfill
      key: customfield_10652
      schema:
        datatype: string
    - name: Affected Table
      key: customfield_10642
      schema:
        datatype: option
    - name: Reason for Backfill
      key: customfield_10651
      schema:
        datatype: option
    - name: Environment Level
      key: customfield_10653
      schema:
        datatype: option
    - name: Other Table Name
      key: customfield_10645
      schema:
        datatype: string
    - name: Permission Change Type
      key: customfield_10648
      schema:
        datatype: option
    - name: Impacted User
      key: customfield_10647
      schema:
        datatype: array
        items: user
    - name: Object Change Type
      key: customfield_10650
      schema:
        datatype: option
  types:
  - id: "10395"
    name: Task
    handle: Task
    subtask: false
  - id: "10396"
    name: Epic
    handle: Epic
    subtask: false
  - id: "10397"
    name: Subtask
    handle: Subtask
    subtask: true
  - id: "10398"
    name: Bug
    handle: Bug
    subtask: false
  - id: "10399"
    name: Story
    handle: Story
    subtask: false
  - id: "10413"
    name: Data Backfill
    handle: Data Backfill
    subtask: false
  - id: "10417"
    name: Permission Change
    handle: Permission Change
    subtask: false
  - id: "10418"
    name: Object Change
    handle: Object Change
    subtask: false
login: jacobo.blanco@paidy.com
project:
  key: DSF
  type: next-gen
server: https://paidy-portal.atlassian.net
